### ISSUE TITLE
fatal error: Rtsp/UDPServer.h no such file or directory

### ISSUE THREAD

**Issue by elvisef** [linkingvision/rapidvms#83]
On i686 Debian v9.1, while doing "make" of "rapidvms", I have two errors:

1) ../groupsock/include/NetCommon.h:94:23: fatal error: sys/types.h: No such file or directory
2) ../main/mediaserver.cpp:26:28: fatal error: Rtsp/UDPServer.h: No such file or directory

In the 1) - In my /usr/lib/ directory I have "i386-linux-gnu" subdirectory. These missing files reside there, in this subdir. When copied to the upper level dir, it goes ok. But how to tell "rapidvms make" to search in the "i386-linux-gnu" subdir as well ? Where to change it ?

In the 2) - I have no idea why it complains about missing RTSP headers. Where they should be ? Generally I did not move any files, so this should not happen I think.

Please advise me as much as You can guys. Thanks.

------------------------------------------
3) Additionally this is weird: /usr/include/gnu/stubs.h:10:27: fatal error: gnu/stubs-64.h: No such file or directory - because my system is 32bit, not 64bit. Why would a 64bit header be needed ?

**Comment by elvisef** [comment]
Ok, for 3), I found a nice solution to install: sudo apt-get install g++-multilib libc6-dev-i386 , so 1) and 3) are done.

Only the 2) is weird for me. I don't know how to make it work.

**Comment by xsmart** [comment]
Could share the build log for the vecvr?

**Comment by elvisef** [comment]
Sure. It's about 3MB so I put it on a share hosting: https://files.fm/u/f2vvvxxe.

**Comment by elvisef** [comment]
Alright, there was no answer since the time I wrote this. Besides, file stored in a link attached is not active anymore (I checked it and it is shown as deleted).

So I am closing the issue..
